package com.mirai.inventoryservice.identity.infrastructure;

import com.mirai.inventoryservice.identity.domain.UserSiteMembership;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Modifying;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;
import org.springframework.transaction.annotation.Transactional;

import java.time.OffsetDateTime;
import java.util.List;
import java.util.Optional;
import java.util.UUID;

@Repository
public interface UserSiteMembershipRepository extends JpaRepository<UserSiteMembership, UUID> {
    Optional<UserSiteMembership> findByUserIdAndSiteId(UUID userId, UUID siteId);
    List<UserSiteMembership> findByUserIdAndIsActiveTrue(UUID userId);
    List<UserSiteMembership> findByUserId(UUID userId);
    boolean existsByUserIdAndSiteIdAndIsActiveTrue(UUID userId, UUID siteId);

    /**
     * Reactivates an existing membership row (or is a no-op if none exists yet - callers pair
     * this with {@link #insertActiveIfAbsent} to cover both "never a member" and
     * "was a member, was revoked"). JPQL bulk updates bypass {@code @UpdateTimestamp}/
     * {@code @Version} entity-listener handling, so {@code updatedAt}/{@code version} are set
     * explicitly here rather than relying on the entity annotations. {@code updatedAt} is a bound
     * parameter, not JPQL's {@code CURRENT_TIMESTAMP} function - that resolves to
     * {@code java.sql.Timestamp}, which Hibernate refuses to assign to the entity's
     * {@code OffsetDateTime} field.
     */
    @Transactional
    @Modifying(clearAutomatically = true)
    @Query("UPDATE UserSiteMembership m SET m.isActive = true, m.updatedAt = :updatedAt, "
            + "m.version = m.version + 1 WHERE m.userId = :userId AND m.siteId = :siteId")
    int activate(@Param("userId") UUID userId, @Param("siteId") UUID siteId, @Param("updatedAt") OffsetDateTime updatedAt);

    /** Returns 0 rows affected when no membership row exists for this pair - callers treat that as "not a member". */
    @Transactional
    @Modifying(clearAutomatically = true)
    @Query("UPDATE UserSiteMembership m SET m.isActive = false, m.updatedAt = :updatedAt, "
            + "m.version = m.version + 1 WHERE m.userId = :userId AND m.siteId = :siteId")
    int deactivate(@Param("userId") UUID userId, @Param("siteId") UUID siteId, @Param("updatedAt") OffsetDateTime updatedAt);

    /**
     * Atomic upsert-as-no-op: two concurrent grant attempts for the same (user, site) pair (e.g.
     * duplicate /sync-user retries) can both read "no row exists" before either writes, per
     * MembershipAuthorizer#grantMainSiteMembershipIfAbsent. A plain find-then-save would let the
     * loser's insert violate the unique constraint at commit and surface as a server error; the
     * unique index itself (not application code) is what makes this correct under concurrency,
     * mirroring the reasoning behind UserRepository#backfillSupabaseUserId.
     * <p>
     * {@code @Transactional} here (not just on the caller): unlike the inherited CRUD methods
     * Spring Data generates, a custom {@code @Modifying @Query} method on the repository
     * interface is not implicitly transactional, so a caller with no transaction of its own
     * (e.g. a repository-level test invoking this directly) would otherwise fail with
     * {@code TransactionRequiredException} rather than exercising the intended race.
     * <p>
     * {@code id} is a bound parameter generated by the caller ({@link #insertActiveIfAbsent})
     * rather than the column's {@code DEFAULT gen_random_uuid()} (set by V52's migration) or an
     * inline {@code gen_random_uuid()} call: this bypasses Hibernate's normal app-side
     * {@code @GeneratedValue} id assignment (needed since this is a native, non-entity insert),
     * and works identically whether the target database has that migration-only default/function
     * or not - H2 test databases (see {@code BaseIntegrationTest}) have neither.
     */
    @Transactional
    @Modifying(clearAutomatically = true)
    @Query(value = "INSERT INTO user_site_memberships (id, user_id, site_id, is_active) "
            + "VALUES (:id, :userId, :siteId, TRUE) ON CONFLICT (user_id, site_id) DO NOTHING",
            nativeQuery = true)
    void insertActiveIfAbsent(@Param("id") UUID id, @Param("userId") UUID userId, @Param("siteId") UUID siteId);

    /** Generates the row id in Java before delegating to the parameterized insert. */
    default void insertActiveIfAbsent(UUID userId, UUID siteId) {
        insertActiveIfAbsent(UUID.randomUUID(), userId, siteId);
    }
}
