package com.mirai.inventoryservice.models.enums;

public enum NotificationType {
    LOW_STOCK,
    OUT_OF_STOCK,
    REORDER_SUGGESTION,
    EXPIRY_WARNING,
    SYSTEM_ALERT,
    SHIPMENT_COMPLETED,
    SHIPMENT_DAMAGED,
    SHIPMENT_DELIVERY_FAILED,
    PACKAGE_ARRIVED,
    DISPLAY_STALE,
    DISPLAY_SET,
    DISPLAY_REMOVED,
    DISPLAY_SWAP,
    DISPLAY_RENEWED
}

